name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Package Repositories
        run: sudo apt-get update

      - name: Set up CMake and Build Essentials
        run: |
          sudo apt-get install -y cmake build-essential

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./RationalThinking_test
