name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: build and run 
      run : |
            mkdir build
            cd build 
            cmake ..
            make
            ./RationalThinking
